travis:
  secure:
    BINSTAR_TOKEN: SXxUwze2zTvzXFRAZ16HBeqo8rSZlgH/S3+/Cl6xHzQDYGDakfzQds7NNxPwtVuoEZ5T8reXTsfv9vV1fnuK7U3TUCFcpvT+qphuB2r3dSUeP6vlhsfV//ojt90HlkcPMTz1L+ZD8n+UbZwLZhLVk3j1GYrYaejvS2UfYWLrBf7sOyv3GpVGOdfW9dUiGoSH2cio7v+cji2d6ep15jPtUWhkeiLZO4nev/saidVzYh7wSlUdBl2rMbdj9kas9NAQU5/pHOGhvqV2sU6a/jdjXHrObNZ3zKi+H1F1DwDTfzyxxrtllwTfYKVOlyoEX57/7nJZJW3jeX08dZ6c/XpN7dZv8B7ulyDL+fcEenBS7NMovXvIaTGPkasn2wReK8VHT9Nkdy030a0NdknO5fFCVjjx0M8YvBk5FyVVIwOQjpqUoks6ANaU1xf8+QUJeNT7w6oRYV92hoaBixR9Y6zmVxDIrS2MitSmkBA2pyfJB6p1QhlduWDEiZ6AsHZl1jF94loaHfGknS7dany5o15thDCP5qT8c0RhGdZIc9d0wK34r+yQQNyXZd4YBWU5A8go2KStmD6fzRxj+Md+2x75PScgci6m2cQnzDixy66kK5pm8ESHcpR1dRF7K6Loi6XA38WR7YAWAA5jDuhCfy7F6tdptCt7crP4BiM6SK1K5dk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
