travis:
  secure:
    BINSTAR_TOKEN: a421VubaD7eXfFnB0CZN6YU+b2lOFle2zgSM5bnahJsoWjrzN32OuyxodYcP5S3nN+mRPd4aGFKPGzDwV9Xm0/cHkmbXu2B3qd9QCHqFyUk+YeOn3qP+5rzMQxez63MRPfq++Pau0FQAIqTizuuIW2n8ODU1UbuFKTC8dMX2olqb9Q71+lXppcvu+o4wzQ7Huwy49JKKZEs22Av2ppOzQgc6duHe0Z2IEdveUCYzt/WsHaph4gIvcaiGQZecasjQ9kuv8ewRGL/2OzmWH+dqJkeenh5cwhozy9ZRHwZF0soA3sSTnau35wUfMrCoxWYqb16RCmP1ojGR5mbQY6IEBYlnjfNDRAsTCiK0bu11ZDolFpLdAUc5RjUdmu/ADWGiOJcXgl3Vm02/LucAi2rf/0zsXuvBFu492C+99SE8SJZP7yRc5wQQUYoFrWsazY2nYutua3TVjUXBIQ9S/gW3lBT6wZJ1kVXyifOVdyLCk4EmTtWufSAiPkCUfXL6g4qSOIGh62FOvBYAEndJjtUu3Qfr1nu9OMG8tmqZtAdpfWoFei75dtqL9qTdBxy40G2kV3v0QWTdFOBLYV9umMg06Vn1Mvaog8+IaXIJvrcd79y6gQvPbMdZ+jkpg2Gamw0l/8dNYiPFbo/ZifDBwrFPwK3APV4ozOiWRHwNo5R2VuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
